name: Build QMK firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
          - lily58

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout userspace
        uses: actions/checkout@v4
        with:
          path: tmp/

      - name: Move file for config
        run: |
          mkdir -p users/${{ github.actor }}
          mv tmp/${{ matrix.file }}/* users/${{ github.actor }}/
          rm -rf tmp

      - name: Build firmware
        run: qmk compile -e CONVERT_TO=rp2040_ce "users/${{ github.actor }}/${{ github.actor }}.json"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        continue-on-error: false
        with:
          name: ${{ matrix.file }}_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2
